server:
  port: 9004
spring:
  application:
    name: cloudalibaba-provider-payment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.104:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'

