server:
  # consul\u670D\u52A1\u7AEF\u53E3
  port: 8006
spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      # consul\u6CE8\u518C\u4E2D\u5FC3\u5730\u5740
      host: 192.168.0.102
      port: 8500
      discovery:
        #hostname: 192.168.0.102
        service-name: ${spring.application.name}
        #\u4E0D\u52A0\u8FD9\u4E2A\u4F1A\u6709\u7EA2\u00D7
        prefer-ip-address: true