server:
  # consul服务端口
  port: 8006
spring:
  application:
    name: consul-provider-payment
  cloud:
    consul:
      # consul注册中心地址
      host: 192.168.0.102
      port: 8500
      discovery:
        #hostname: 192.168.0.102
        service-name: ${spring.application.name}
        #不加这个会有红×
        prefer-ip-address: true